"""
PlatformIO pre-build script: Generate WiFi credentials header from CSV.

Reads wifi_config.csv → generates include/wifi_credentials.gen.h
Both files are gitignored. The .csv.example template is in git.
"""

Import("env")

import csv
import os
import sys


def djb2_hash(s):
    """DJB2 hash matching the C implementation in wifi_ssid_map.c."""
    h = 5381
    for c in s:
        h = ((h << 5) + h + ord(c)) & 0xFFFFFFFF
    return h


def generate_header(csv_path, header_path):
    entries = []

    if os.path.exists(csv_path):
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            for row in reader:
                # Skip empty lines and comments
                if not row or row[0].strip().startswith("#"):
                    continue
                ssid = row[0].strip()
                password = row[1].strip() if len(row) > 1 else ""
                if ssid:
                    entries.append((ssid, password))
        print(f"[gen_wifi_creds] Loaded {len(entries)} credentials from {csv_path}")
    else:
        print(
            f"[gen_wifi_creds] WARNING: {csv_path} not found. "
            "Building with 0 WiFi credentials. "
            "Copy wifi_config.csv.example to wifi_config.csv and fill in your networks.",
            file=sys.stderr,
        )

    # Compute combined hash for change detection
    combined = "".join(f"{s}:{p};" for s, p in entries)
    cred_hash = djb2_hash(combined) if entries else 0

    # Generate header
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/gen_wifi_creds.py — DO NOT EDIT\n")
        f.write("// Source: wifi_config.csv\n\n")
        f.write("#pragma once\n\n")
        f.write(f"#define WIFI_CRED_COUNT {len(entries)}\n")
        f.write(f"#define WIFI_CRED_HASH  0x{cred_hash:08X}u\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *ssid;\n")
        f.write("    const char *pass;\n")
        f.write("} wifi_cred_compiled_t;\n\n")
        if entries:
            f.write(
                "static const wifi_cred_compiled_t WIFI_CRED_LIST[] = {\n"
            )
            for ssid, password in entries:
                # Escape backslashes and quotes for C string
                s = ssid.replace("\\", "\\\\").replace('"', '\\"')
                p = password.replace("\\", "\\\\").replace('"', '\\"')
                f.write(f'    {{"{s}", "{p}"}},\n')
            f.write("};\n")
        else:
            f.write("static const wifi_cred_compiled_t *WIFI_CRED_LIST = NULL;\n")

    print(f"[gen_wifi_creds] Generated {header_path} (hash=0x{cred_hash:08X})")


# --- Entry point ---
project_dir = env.subst("$PROJECT_DIR")
csv_path = os.path.join(project_dir, "wifi_config.csv")
header_path = os.path.join(project_dir, "include", "wifi_credentials.gen.h")

generate_header(csv_path, header_path)
